name: Code formatting check

on:
  pull_request:

# Cancel previous runs if a more recent commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  clang-format-check:
    runs-on: "ubuntu-20.04"
    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.15
      with:
        source: '.'
        exclude: './third_party'
        clangFormatVersion: 16
