name: Linux build

on:
  pull_request:

# Cancel previous runs if a more recent commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  linux-build:
    name: Build and run tests on Linux
    runs-on: "ubuntu-22.04"
    steps:
      - name: Setup necessary packages
        run: |
          sudo apt update && sudo apt install libxrandr-dev libxinerama-dev libx11-dev libxcursor-dev libxi-dev libx11-xcb-dev clang \
          mesa-vulkan-drivers
      - name: Setup Vulkan SDK
        run: |
          wget -q https://sdk.lunarg.com/sdk/download/1.3.216.0/linux/vulkansdk-linux-x86_64-1.3.216.0.tar.gz
          if ! echo "2cb10cb94ac656e9e454f1f5ae48e8a833253af5fe22562d27310db45b579212 vulkansdk-linux-x86_64-1.3.216.0.tar.gz" | sha256sum -c --status; then
            echo "Invalid SHA256 for VulkanSDK's binary. Aborting."
            exit 1
          fi
          mkdir "${HOME}/vulkan-sdk"
          tar -xf vulkansdk-linux-x86_64-1.3.216.0.tar.gz -C "${HOME}/vulkan-sdk"
          echo "VULKAN_SDK=${HOME}/vulkan-sdk/1.3.216.0/x86_64" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Switch to pull request branch and clone submodules
        run: |
          git checkout ${GITHUB_SHA}
          git submodule update --init --recursive
      - name: Build
        run: |
          mkdir build
          cd build
          # -DBUILD_TESTS=OFF only disables the OpenXR tests
          cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DPPX_BUILD_TESTS=OFF -DPPX_BUILD_XR=0 -DBUILD_TESTS=OFF
          make -j $(nproc)